# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cbf6ec0a641a18e135f1626f38b3c18b7e012d1a42d5c34d01892acc361e56485cd65f171c3ee3609c908576ba2ba83124377053852161608e1dfc380d5c731

test:
  secret_key_base: 85fbeb404e920b8e4feaaacb1e32daf4d775e6162571f6ee6302ba79899042624ec5250361805b6f930ba800e24b523f1af9f83b988b8546d8f348509268e676

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
